namespace NodeJS {
  interface ProcessEnv {
    EXTERNAL_API_CRAWL?: string;
    EXTERNAL_API_FSFSSFSSFSFSFS?: string;
    NEXT_PUBLIC_BASE_URL?: string;
    NEXT_PUBLIC_EXTERNAL_API_CRAWL?: string;
    NEXT_PUBLIC_EXTERNAL_API_FSFSSFSSFSFSFS?: string;
    NEXT_PUBLIC_FIREBASE_API_KEY?: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
    NEXT_PUBLIC_FIREBASE_DATABASE_URL?: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID?: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    NEXT_PUBLIC_FIREBASE_APP_ID?: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_VAPID_KEY?: string;
    NEXT_PUBLIC_WEATHER_API_KEY?: string;
  }
}
